format_version: 2
environments:
  ci:
    pipelines:
      - "team2API"
      
pipelines:
  "team2API":
    group: team2
    materials:
      ui:
        git: "git@github.com:jawahars16/justcinemas-api.git"
    stages:
      - buildAndTest:
          jobs:
            test:
              resources:
                - node-and-java
              tasks:
                - script: |
                    /scripts/buildJava.sh buildAndDeploy/build/build.sh team2

      - deploy:
           jobs:
            deploy:
              resources:
                - node-and-java
              tasks:
                - script: |
                    buildAndDeploy/deploy/deploy.sh team2 sethu-origin-key-pair
